name: Run Gradle on PRs
on:
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
        
    - name: Execute Gradle build
      run: ./gradlew build
